### Day 1: NumPy Basics

In [9]:
# Importing numpy library
import numpy as np

In [10]:
# Creating an array from list
lst = [1,2,3,4,5]
np_arr = np.array(lst)
np_arr

array([1, 2, 3, 4, 5])

In [11]:
# Printing the data type
print(type(np_arr))

<class 'numpy.ndarray'>


In [12]:
# Accessing elements in the array by index
np_arr[3]

4

In [13]:
# Multiplying the array with a constant
np_arr2 = np_arr * 2
np_arr2

array([ 2,  4,  6,  8, 10])

In [14]:
# Selection using condition
a = np_arr < 3
print(a)

[ True  True False False False]


In [15]:
# Selection using square brackets, SUBSETTING
np_arr[a]

array([1, 2])

In [16]:
# Arithmetic operators on numpy arrays
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [17]:
# Elements with different data types, TYPE COERCION
np.array([1,4,'Hi',True])

array(['1', '4', 'Hi', 'True'], dtype='<U11')

### Day 2: NumPy

In [18]:
np_arr

array([1, 2, 3, 4, 5])

In [19]:
# Slicing
print(np_arr[1:3])

[2 3]


In [20]:
# Dictionary to numpy arrays
std = {1:'Ram',2:'Sita',3:'Gita'}
np_std = np.array(std)
np_std

array({1: 'Ram', 2: 'Sita', 3: 'Gita'}, dtype=object)

In [21]:
# Verifying type
print(type(np_std))

<class 'numpy.ndarray'>


In [22]:
# Finding size
np_std.size

1

In [23]:
# Finding data type
np_std.dtype

dtype('O')

In [24]:
# Accessing specific element
extracted_dict = np_std.item()
extracted_dict[2]

'Sita'

In [25]:
# Creating 2D Array
lst_2d = [[1,2,3],[4,5,6]]
np_2d = np.array(lst_2d)
np_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# Accessing specific element in 2d array
lst_2d[0][2]

3

### Day 3: NumPy

In [28]:
# Create an array filled with zeroes
np.zeros([2,2],int)

array([[0, 0],
       [0, 0]])

In [39]:
# Create an array filled with zeroes
np.zeros((2,2), dtype = int)

array([[0, 0],
       [0, 0]])

In [38]:
# Create an array filled with ones
np.ones((4,5), int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
# Creating an array filled with custom elements
np.full((3,3),7,int)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [43]:
# Creating an empty array with 2 elements
np.empty(2) # might vary

array([8.52586116e-312, 0.00000000e+000])

In [46]:
# Using arange
try_arange = np.arange(4,13,3)
try_arange

array([ 4,  7, 10])

In [47]:
# Sorting the elements
np.sort(try_arange)

array([ 4,  7, 10])

In [52]:
# Concatenate Error: arrays must have same dimension
a = np.array([[1,2,3],[4,5,6]])
b = np.array([7,8,9])
np.concatenate((a,b))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [60]:
# Concatenate 2d array
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9]])
x = np.concatenate((a,b))
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
# Arithmetic operators on 2d array
a + b

array([[ 8, 10, 12],
       [11, 13, 15]])

In [54]:
# Concatenate 1d array
c = np.array([1, 2, 3, 4])
d = np.array([5, 6, 7, 8])
np.concatenate((c,d))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
# Arithmetic operators on 1d array
c + d

array([ 6,  8, 10, 12])

In [70]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
# Finding dimension
x.ndim

2

In [65]:
# Finding shape
x.shape

(3, 3)

In [66]:
# Finding size
x.size

9

In [72]:
# Creating an array to reshape
old_array = np.arange(8)
old_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [76]:
# Reshaping the existing array
new_array = np.reshape(old_array, (4,2))
new_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [77]:
# Reshaping Error: No. of elements specified not matched with the np. of elements in the original array
new_array = np.reshape(old_array, (2,2))
new_array

ValueError: cannot reshape array of size 8 into shape (2,2)

#### Basic Array Operations

In [99]:
c, d

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [93]:
c + d

array([ 6,  8, 10, 12])

In [94]:
c - d

array([-4, -4, -4, -4])

In [95]:
c * d

array([ 5, 12, 21, 32])

In [96]:
c/d

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [97]:
c%d

array([1, 2, 3, 4])

In [98]:
c**d

array([    1,    64,  2187, 65536])