### Day 1: NumPy Basics

In [40]:
# Importing numpy library
import numpy as np

In [41]:
# Creating an array from list
lst = [1,2,3,4,5]
np_arr = np.array(lst)
np_arr

array([1, 2, 3, 4, 5])

In [42]:
# Printing the data type
print(type(np_arr))

<class 'numpy.ndarray'>


In [43]:
# Accessing elements in the array by index
np_arr[3]

4

In [44]:
# Multiplying the array with a constant
np_arr2 = np_arr * 2
np_arr2

array([ 2,  4,  6,  8, 10])

In [45]:
# Selection using condition
a = np_arr < 3
print(a)

[ True  True False False False]


In [46]:
# Selection using square brackets, SUBSETTING
np_arr[a]

array([1, 2])

In [47]:
# Arithmetic operators on numpy arrays
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [48]:
# Elements with different data types, TYPE COERCION
np.array([1,4,'Hi',True])

array(['1', '4', 'Hi', 'True'], dtype='<U11')

### Day 2: NumPy

In [49]:
np_arr

array([1, 2, 3, 4, 5])

In [50]:
# Slicing
print(np_arr[1:3])

[2 3]


In [51]:
# Dictionary to numpy arrays
std = {1:'Ram',2:'Sita',3:'Gita'}
np_std = np.array(std)
np_std

array({1: 'Ram', 2: 'Sita', 3: 'Gita'}, dtype=object)

In [52]:
# Verifying type
print(type(np_std))

<class 'numpy.ndarray'>


In [53]:
# Finding size
np_std.size

1

In [54]:
# Finding data type
np_std.dtype

dtype('O')

In [55]:
# Accessing specific element
extracted_dict = np_std.item()
extracted_dict[2]

'Sita'

In [56]:
# Creating 2D Array
lst_2d = [[1,2,3],[4,5,6]]
np_2d = np.array(lst_2d)
np_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
# Accessing specific element in 2d array
lst_2d[0][2]

3

### Day 3: NumPy

In [58]:
# Create an array filled with zeroes
np.zeros([2,2],int)

array([[0, 0],
       [0, 0]])

In [59]:
# Create an array filled with zeroes
np.zeros((2,2), dtype = int)

array([[0, 0],
       [0, 0]])

In [60]:
# Create an array filled with ones
np.ones((4,5), int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [61]:
# Creating an array filled with custom elements
np.full((3,3),7,int)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [62]:
# Creating an empty array with 2 elements
np.empty(2) # might vary

array([1.34221126e-311, 0.00000000e+000])

In [63]:
# Using arange
try_arange = np.arange(4,13,3)
try_arange

array([ 4,  7, 10])

In [64]:
# Sorting the elements
np.sort(try_arange)

array([ 4,  7, 10])

In [65]:
# Concatenate Error: arrays must have same dimension
a = np.array([[1,2,3],[4,5,6]])
b = np.array([7,8,9])
np.concatenate((a,b))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [66]:
# Concatenate 2d array
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9]])
x = np.concatenate((a,b))
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
# Arithmetic operators on 2d array
a + b

array([[ 8, 10, 12],
       [11, 13, 15]])

In [68]:
# Concatenate 1d array
c = np.array([1, 2, 3, 4])
d = np.array([5, 6, 7, 8])
np.concatenate((c,d))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
# Arithmetic operators on 1d array
c + d

array([ 6,  8, 10, 12])

In [70]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
# Finding dimension
x.ndim

2

In [72]:
# Finding shape
x.shape

(3, 3)

In [73]:
# Finding size
x.size

9

In [74]:
# Creating an array to reshape
old_array = np.arange(8)
old_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [75]:
# Reshaping the existing array
new_array = np.reshape(old_array, (4,2))
new_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [76]:
# Reshaping Error: No. of elements specified not matched with the np. of elements in the original array
new_array = np.reshape(old_array, (2,2))
new_array

ValueError: cannot reshape array of size 8 into shape (2,2)

#### Basic Array Operations

In [77]:
c, d

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [78]:
c + d

array([ 6,  8, 10, 12])

In [79]:
c - d

array([-4, -4, -4, -4])

In [80]:
c * d

array([ 5, 12, 21, 32])

In [81]:
c/d

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [82]:
c%d

array([1, 2, 3, 4])

In [83]:
c**d

array([    1,    64,  2187, 65536])

### Day 4: Pandas

In [84]:
import pandas as pd

In [85]:
# DataFrame
pd.DataFrame({'Eng': [50, 21], 'Maths': [11, 56]})

Eng  Maths
0   50     11
1   21     56

In [86]:
# Assigning index
pd.DataFrame({'Ram': ['I liked it.', 'It was awful.'], 
              'Shyam': ['Pretty good.', 'Bland.']},
             index=['Icecream', 'Pizza'])

Ram         Shyam
Icecream    I liked it.  Pretty good.
Pizza     It was awful.        Bland.

In [87]:
# Series
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [88]:
# Assigning index
pd.Series([1, 2, 3, 4, 5], index = [2020,2021,2022,2023,2024])

2020    1
2021    2
2022    3
2023    4
2024    5
dtype: int64

In [90]:
# Reading data files
df = pd.read_csv('info.csv')
df

Name   Age Sex
0    Ram  29.0   M
1  Shyam  22.0   M
2   Sita  27.0   F
3   Hari  27.0   M
4   Rita  24.0   F
5   Gita   NaN   F

In [91]:
# head command
df.head()

Name   Age Sex
0    Ram  29.0   M
1  Shyam  22.0   M
2   Sita  27.0   F
3   Hari  27.0   M
4   Rita  24.0   F

In [92]:
df.head(2)

Name   Age Sex
0    Ram  29.0   M
1  Shyam  22.0   M

In [93]:
df.shape

(6, 3)

In [94]:
df.size

18

In [96]:
df.ndim

2