### Day 1: NumPy Basics

In [1]:
# Importing numpy library
import numpy as np

In [2]:
# Creating an array from list
lst = [1,2,3,4,5]
np_arr = np.array(lst)
np_arr

array([1, 2, 3, 4, 5])

In [3]:
# Printing the data type
print(type(np_arr))

<class 'numpy.ndarray'>


In [4]:
# Accessing elements in the array by index
np_arr[3]

4

In [5]:
# Multiplying the array with a constant
np_arr2 = np_arr * 2
np_arr2

array([ 2,  4,  6,  8, 10])

In [6]:
# Selection using condition
a = np_arr < 3
print(a)

[ True  True False False False]


In [7]:
# Selection using square brackets, SUBSETTING
np_arr[a]

array([1, 2])

In [8]:
# Arithmetic operators on numpy arrays
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [9]:
# Elements with different data types, TYPE COERCION
np.array([1,4,'Hi',True])

array(['1', '4', 'Hi', 'True'], dtype='<U11')

### Day 2: NumPy

In [11]:
np_arr

array([1, 2, 3, 4, 5])

In [10]:
# Slicing
print(np_arr[1:3])

[2 3]


In [12]:
# Dictionary to numpy arrays
std = {1:'Ram',2:'Sita',3:'Gita'}
np_std = np.array(std)
np_std

array({1: 'Ram', 2: 'Sita', 3: 'Gita'}, dtype=object)

In [13]:
# Verifying type
print(type(np_std))

<class 'numpy.ndarray'>


In [17]:
# Finding size
np_std.size

1

In [18]:
# Finding data type
np_std.dtype

dtype('O')

In [30]:
# Accessing specific element
extracted_dict = np_std.item()
extracted_dict[2]

'Sita'

In [25]:
# Creating 2D Array
lst_2d = [[1,2,3],[4,5,6]]
np_2d = np.array(lst_2d)
np_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# Accessing specific element in 2d array
lst_2d[0][2]

3