### Day 1: NumPy Basics

In [1]:
# Importing numpy library
import numpy as np

In [2]:
# Creating an array from list
lst = [1,2,3,4,5]
np_arr = np.array(lst)
np_arr

array([1, 2, 3, 4, 5])

In [3]:
# Printing the data type
print(type(np_arr))

<class 'numpy.ndarray'>


In [4]:
# Accessing elements in the array by index
np_arr[3]

4

In [6]:
# Multiplying the array with a constant
np_arr2 = np_arr * 2
np_arr2

array([ 2,  4,  6,  8, 10])

In [7]:
# Selection using condition
a = np_arr < 3
print(a)

[ True  True False False False]


In [8]:
# Selection using square brackets, SUBSETTING
np_arr[a]

array([1, 2])

In [10]:
# Arithmetic operators on numpy arrays
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [11]:
# Elements with different data types, TYPE COERCION
np.array([1,4,'Hi',True])

array(['1', '4', 'Hi', 'True'], dtype='<U11')